//! Deterministic generators for the pre-commit and CI enforcement planes.
//!
//! Each takes a [`Policy`](crate::Policy) and returns the exact file content as
//! a string. Pure and stable: the same policy yields byte-identical output, so
//! `aoa policy compile` re-runs are no-op diffs. Generated files carry a header
//! marking them machine-owned (edit `aoa-policy.yaml`, not the artifact).

use crate::Policy;

/// Header stamped on every generated artifact so a reader (human or agent) knows
/// it is derived and where the source of truth lives.
const PROVENANCE: &str =
    "# GENERATED by `aoa policy compile` from aoa-policy.yaml — edit the policy, not this file.";

/// The `.pre-commit-config.yaml` plane: a local hook that rejects a commit
/// touching any protected path. Bypassable with `--no-verify` by design; CI is
/// the backstop.
pub fn precommit_config(policy: &Policy) -> String {
    let mut out = format!("{PROVENANCE}\n");
    out.push_str("repos:\n");
    out.push_str("  - repo: local\n");
    out.push_str("    hooks:\n");
    out.push_str("      - id: aoa-protected-paths\n");
    out.push_str("        name: AOA protected-path guard\n");
    out.push_str("        entry: aoa policy guard-staged\n");
    out.push_str("        language: system\n");
    out.push_str("        pass_filenames: true\n");
    out.push_str(&files_comment(policy));
    out
}

/// The CI plane: a GitHub Actions workflow that fails the run if a changed file
/// matches a protected path. The unbypassable backstop.
pub fn ci_workflow(policy: &Policy) -> String {
    let globs = bash_glob_list(&policy.protected_paths);
    format!(
        "{PROVENANCE}\n\
name: AOA Policy\n\
on: [pull_request]\n\
jobs:\n\
  protected-paths:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
        with:\n\
          fetch-depth: 0\n\
      - name: Reject writes to protected paths\n\
        run: |\n\
          protected=({globs})\n\
          changed=$(git diff --name-only origin/${{{{ github.base_ref }}}}...HEAD)\n\
          fail=0\n\
          for f in $changed; do\n\
            for p in \"${{protected[@]}}\"; do\n\
              case \"$f\" in $p) echo \"protected path modified: $f (matches $p)\"; fail=1;; esac\n\
            done\n\
          done\n\
          exit $fail\n",
    )
}

/// The `CODEOWNERS` spine from the mutation-gateway allowlist: every gateway
/// module requires owner review. Empty allowlist yields a header-only file.
pub fn codeowners(policy: &Policy) -> String {
    let mut out = format!("{PROVENANCE}\n");
    for module in &policy.gateway_allowlist {
        out.push_str(&format!("{module} @owners\n"));
    }
    out
}

/// Render the protected globs as a space-separated bash array body, each
/// single-quoted so a glob is passed literally to `case`.
fn bash_glob_list(globs: &[String]) -> String {
    globs
        .iter()
        .map(|g| format!("'{g}'"))
        .collect::<Vec<_>>()
        .join(" ")
}

/// A trailing comment listing the protected globs, so the generated pre-commit
/// file is self-documenting without changing its executable behavior.
fn files_comment(policy: &Policy) -> String {
    if policy.protected_paths.is_empty() {
        "        # no protected paths declared\n".to_string()
    } else {
        format!(
            "        # protected: {}\n",
            policy.protected_paths.join(", ")
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Policy {
        Policy::from_yaml(
            "protected_paths: [\"migrations/**\", \".github/**\"]\n\
             gateway_allowlist: [\"src/db/gateway.rs\"]\n",
        )
        .unwrap()
    }

    #[test]
    fn generators_are_deterministic() {
        let p = sample();
        assert_eq!(precommit_config(&p), precommit_config(&p));
        assert_eq!(ci_workflow(&p), ci_workflow(&p));
        assert_eq!(codeowners(&p), codeowners(&p));
    }

    #[test]
    fn every_artifact_carries_the_provenance_header() {
        let p = sample();
        assert!(precommit_config(&p).starts_with(PROVENANCE));
        assert!(ci_workflow(&p).starts_with(PROVENANCE));
        assert!(codeowners(&p).starts_with(PROVENANCE));
    }

    #[test]
    fn ci_workflow_embeds_each_protected_glob() {
        let ci = ci_workflow(&sample());
        assert!(ci.contains("'migrations/**'"));
        assert!(ci.contains("'.github/**'"));
    }

    #[test]
    fn codeowners_lists_each_gateway() {
        let owners = codeowners(&sample());
        assert!(owners.contains("src/db/gateway.rs @owners"));
    }

    #[test]
    fn empty_policy_yields_header_only_codeowners() {
        let owners = codeowners(&Policy::default());
        assert_eq!(owners, format!("{PROVENANCE}\n"));
    }
}
